languages:
  JavaScript: true
  PHP: true
exclude_paths:
- "assets/js/socket.io.js"
- "assets/js/head/modernizr.min.js"
- "assets/js/scoring/mithril.js"
- "app/check.php"
- "app/SymfonyRequirements.php"
- "app/DoctrineMigrations/*.php"
- "web/app.php"
- "web/app_dev.php"