language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

addons:
  code_climate:
    repo_token: 898149e74d4bf6bfd0ba331b38cc2d7f9aa01d582d594a821330937eeaf5e0b1

install: composer install --prefer-dist

before_script: ./travis-pre-script.sh

script: phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/codeclimate/php-test-reporter/composer/bin/test-reporter
