sudo: false

language: php
php:
  - 5.5
  - 5.6
  - 7.0

addons:
  code_climate:
    repo_token: 898149e74d4bf6bfd0ba331b38cc2d7f9aa01d582d594a821330937eeaf5e0b1

install: composer install --prefer-dist

before_script:
  - phpenv config-rm xdebug.ini
  - 'sed -i -e ''s/user:.*/user: travis/'' app/config/config_test.yml'
  - 'sed -i -e ''s/password:.*/password: ~/'' app/config/config_test.yml'


script: phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/codeclimate/php-test-reporter/composer/bin/test-reporter

cache:
  directories:
    - $HOME/.composer/cache
