# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    orbital.authenticator:
        class: AppBundle\Services\Security\PamAuthenticator
        arguments: ["@security.password_encoder", "@doctrine"]

    orbital.person_importer:
        class: AppBundle\Services\Importing\PersonImporter
        arguments: ["@doctrine"]

# handicaps
    orbital.handicap.calculate:
        class: AppBundle\Services\Handicap\HandicapCalculator

    orbital.handicap.manager:
        class: AppBundle\Services\Handicap\HandicapManager
        arguments: ["@doctrine"]

# twig extensions
    orbital.twig.enum:
        class: AppBundle\Services\Twig\EnumExtension
        public: false
        tags:
            - { name: twig.extension }
    orbital.twig.measure:
        class: AppBundle\Services\Twig\MeasureExtension
        public: false
        tags:
            - { name: twig.extension }