# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    orbital.authenticator:
        class: AppBundle\Services\Security\PamAuthenticator
        arguments: ["@security.password_encoder", "@doctrine"]
    orbital.person_importer:
        class: AppBundle\Services\Importing\PersonImporter
        arguments: ["@doctrine"]

# handicaps
    orbital.handicap.calculate:
        class: AppBundle\Services\Handicap\HandicapCalculator
    orbital.handicap.manager:
        class: AppBundle\Services\Handicap\HandicapManager
        arguments: ["@doctrine", "@orbital.handicap.calculate"]
    orbital.handicap.listener:
        class: AppBundle\Services\Handicap\HandicapListener
        arguments: ["@orbital.handicap.manager", "@doctrine"]
        tags:
            - { name: kernel.event_listener, event: 'orbital.events.score_create', method: score_create }
            - { name: kernel.event_listener, event: 'orbital.events.score_update', method: score_update }

# events
    orbital.events.doctrine:
        class: AppBundle\Services\Events\DoctrineListener
        arguments: ["@event_dispatcher"]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }

# twig extensions
    orbital.twig.enum:
        class: AppBundle\Services\Twig\EnumExtension
        public: false
        tags:
            - { name: twig.extension }
    orbital.twig.measure:
        class: AppBundle\Services\Twig\MeasureExtension
        public: false
        tags:
            - { name: twig.extension }